### PR TITLE
Add fixes for CI

### PR DESCRIPTION
**Pull request by superkhau**
- Update LICENSE file
- Add smoke test

### CODE REVIEW

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@rmg Why is this failing?

**Comment by rmg** [comment]
@superkhau because the version of strong-oracle used by loopback-connector-oracle doesn't support node-v4.

**Comment by superkhau** [comment]
@rmg TY, it's a known limitation so I will merge.

**Pull request merged**
